## The below is a small project to understand the use pandas for Geocoding the addresses with help of Python. 

### The process to convert the address to Coordinates is called <u> GeoCoding</u>
### And if we need to convert coordinates to Address, then it is called <u> Reverse Geocoding </u>

We use Geopy for doing the Geocoding. For that please use <b> PIP INSTALL GEOPY </b>

In [77]:
pip install geopy

Note: you may need to restart the kernel to use updated packages.


In [79]:
import geopy
dir(geopy)

['ArcGIS',
 'AzureMaps',
 'BANFrance',
 'Baidu',
 'Bing',
 'DataBC',
 'GeoNames',
 'GeocodeEarth',
 'GeocodeFarm',
 'Geolake',
 'GoogleV3',
 'Here',
 'IGNFrance',
 'LiveAddress',
 'Location',
 'MapBox',
 'Nominatim',
 'OpenCage',
 'OpenMapQuest',
 'Pelias',
 'Photon',
 'PickPoint',
 'Point',
 'Timezone',
 'TomTom',
 'What3Words',
 'Yandex',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'compat',
 'exc',
 'format',
 'geocoders',
 'get_geocoder_for_service',
 'location',
 'point',
 'timezone',
 'units',
 'util']

For our purpose, here we use geocoders and ArcGIS in our code

In [81]:
from geopy.geocoders import ArcGIS
nom=ArcGIS()

In [83]:
#How to find longitude and latitude from the given address
nom.geocode('3666 21st St,San Francisco,CA 94114')

Location(3666 21st St, San Francisco, California, 94114, (37.7564496899993, -122.42936434915458, 0.0))

In [85]:
#Let us know store the above result in a variable.
n = nom.geocode('3666 21st St,San Francisco,CA 94114')
n.latitude

37.7564496899993

In [86]:
n.longitude

-122.42936434915458

In [87]:
type(n)

geopy.location.Location

In [89]:
#The below code will add the latitude and longitude column to the dataframe
import pandas as pd
df = pd.read_csv("C:/Users/Rajesh/Downloads/supermarkets.csv")
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [90]:
df['Address']=df['Address'] + "," + df['City']+ "," +df['State']+ ","+df['Country']
df

ID                                         Address           City  \
0   1         3666 21st St,San Francisco,CA 94114,USA  San Francisco   
1   2       735 Dolores St,San Francisco,CA 94119,USA  San Francisco   
2   3  332 Hill St,San Francisco,California 94114,USA  San Francisco   
3   4         3995 23rd St,San Francisco,CA 94114,USA  San Francisco   
4   5    1056 Sanchez St,San Francisco,California,USA  San Francisco   
5   6      551 Alvarado St,San Francisco,CA 94114,USA  San Francisco   

              State Country         Name  Employees  
0          CA 94114     USA      Madeira          8  
1          CA 94119     USA  Bready Shop         15  
2  California 94114     USA  Super River         25  
3          CA 94114     USA   Ben's Shop         10  
4        California     USA      Sanchez         12  
5          CA 94114     USA   Richvalley         20

In [93]:
df['Coordinates']=df['Address'].apply(nom.geocode) # 'apply' is a pandas method
df['Coordinates']

0    (3666 21st St, San Francisco, California, 9411...
1    (735 Dolores St, San Francisco, California, 94...
2    (332 Hill St, San Francisco, California, 94114...
3    (3995 23rd St, San Francisco, California, 9411...
4    (1056 Sanchez St, San Francisco, California, 9...
5    (551 Alvarado St, San Francisco, California, 9...
Name: Coordinates, dtype: object

In [96]:
df['Coordinates'][0].latitude

37.7564496899993

In [97]:
df['Coordinates'][0].longitude

-122.42936434915458

In [98]:
df

ID                                         Address           City  \
0   1         3666 21st St,San Francisco,CA 94114,USA  San Francisco   
1   2       735 Dolores St,San Francisco,CA 94119,USA  San Francisco   
2   3  332 Hill St,San Francisco,California 94114,USA  San Francisco   
3   4         3995 23rd St,San Francisco,CA 94114,USA  San Francisco   
4   5    1056 Sanchez St,San Francisco,California,USA  San Francisco   
5   6      551 Alvarado St,San Francisco,CA 94114,USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates  
0  (3666 21st St, San Francisco, California, 9411...  
1  (735 Dolores St, San Francisco, California, 94...  
2  (332 Hill St, San Francisco, California, 94114...  
3  (3995 23rd St, San Francisco, California, 9411...  
4  (1056 Sanchez St, San Francisco, California, 9...  
5  (551 Alvarado St, San Francisco, California, 9...

In [99]:
#Adding latitude and longitude to the dataframe
df['Lalitude']=df['Coordinates'].apply(lambda x: x.latitude if x !=None else None)
df['Longitude']=df['Coordinates'].apply(lambda x: x.longitude if x !=None else None)
df

ID                                         Address           City  \
0   1         3666 21st St,San Francisco,CA 94114,USA  San Francisco   
1   2       735 Dolores St,San Francisco,CA 94119,USA  San Francisco   
2   3  332 Hill St,San Francisco,California 94114,USA  San Francisco   
3   4         3995 23rd St,San Francisco,CA 94114,USA  San Francisco   
4   5    1056 Sanchez St,San Francisco,California,USA  San Francisco   
5   6      551 Alvarado St,San Francisco,CA 94114,USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates   Lalitude   Longitude  
0  (3666 21st St, San Francisco, California, 9411...  37.756450 -122.429364  
1  (735 Dolores St, San Francisco, California, 94...  37.757796 -122.425597  
2  (332 Hill St, San Francisco, California, 94114...  37.755648 -122.428803  
3  (3995 23rd St, San Francisco, California, 9411...  37.752991 -122.431702  
4  (1056 Sanchez St, San Francisco, California, 9...  37.752129 -122.430028  
5  (551 Alvarado St, San Francisco, California, 9...  37.753719 -122.433240

In case, If there is a need to understand pandas more, just an overview on Pandas/Numpy is given below. 




<b>///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////</b>

##                        PANDAS ILLUSTRATIONS

In [21]:
import os
print (os.getcwd())  #get the current working directory

C:\Users\Rajesh


In [22]:
os.chdir('C:/Users/Rajesh/Downloads/') #To change the directory

In [23]:
os.listdir() #list the file present on thsi location

['!qhlogs.doc',
 'Anaconda3-2019.10-Windows-x86_64.exe',
 'data.json',
 'data.txt',
 'desktop.ini',
 'Intel Driver and Support Assistant',
 'smallgray.png',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx']

In [24]:
#Loading a CSV file
import pandas as pd
df1= pd.read_csv("supermarkets.csv")
df1
#df1 is called as the dataframe

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [6]:
#Loading a JSON file
df2=pd.read_json("supermarkets.json")
df2.set_index('ID')

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [9]:
#Loading a Excel file. Please specify the sheet name if needed.. If not it will take the first sheet by default
df3=pd.read_excel("supermarkets.xlsx", sheet_name=0)
df3

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [12]:
#Please find below df4 and df5 in the next line item. 
#Here, .txt file is read by read_csv. This is because we have commas as separator. so we are not using 'sep' keyword here.
#Kindly follow the below (df5) where we would use sep keyword
df4=pd.read_csv("supermarkets-commas.txt")
df4

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [13]:
#Please see that the below data frame is not in a readable format. It looks very clumsy. 
#So, what can we do now?
df5=pd.read_csv("supermarkets-semi-colons.txt")
df5

ID;Address;City;State;Country;Name;Employees
0  1;3666 21st St;San Francisco;CA 94114;USA;Made...
1  2;735 Dolores St;San Francisco;CA 94119;USA;Br...
2  3;332 Hill St;San Francisco;California 94114;U...
3  4;3995 23rd St;San Francisco;CA 94114;USA;Ben'...
4  5;1056 Sanchez St;San Francisco;California;USA...
5  6;551 Alvarado St;San Francisco;CA 94114;USA;R...

In [14]:
#Let us now add the 'sep' keyword to make it into a readable manner
df5=pd.read_csv("supermarkets-semi-colons.txt", sep=";")
df5

ID          Address           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

#### Loading Text Files

In [19]:
#Now let us load a text file. The text file contains no headers and takes one of the line as headers. 
#No we will add headers to the below dataframe.
df8=pd.read_csv("data.txt")
df8

1     3666 21st St  San Francisco          CA 94114  USA      Madeira   8
0  2   735 Dolores St  San Francisco          CA 94119  USA  Bready Shop  15
1  3      332 Hill St  San Francisco  California 94114  USA  Super River  25
2  4     3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop  10
3  5  1056 Sanchez St  San Francisco        California  USA      Sanchez  12
4  6  551 Alvarado St  San Francisco          CA 94114  USA   Richvalley  20

#### Set Header rows 

In [21]:
#Set the headers to None.Python now gives a default header with numbers.  So now, add the column name to headers
df8=pd.read_csv("data.txt", header=None)
df8

0                1              2                 3    4            5   6
0  1     3666 21st St  San Francisco          CA 94114  USA      Madeira   8
1  2   735 Dolores St  San Francisco          CA 94119  USA  Bready Shop  15
2  3      332 Hill St  San Francisco  California 94114  USA  Super River  25
3  4     3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop  10
4  5  1056 Sanchez St  San Francisco        California  USA      Sanchez  12
5  6  551 Alvarado St  San Francisco          CA 94114  USA   Richvalley  20

#### Set Columns

In [22]:
#Set Column names
df8.columns=['ID', 'Address', 'City', 'Zip', 'Country','Name','Employees']
df8
#Hence the column names are set

ID          Address           City               Zip Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

#### Set Index

In [26]:
#Please note the above dataframe has a default index assigned with numbers. Hence let us now set the index.
df8.set_index("ID")
#Here, we need to note one thing. The set index does not change the shape of dataframe. df8 remains the same even after we set
#index. Unless we make an argument inplace=True, then the dataframe willnot change. 

Address           City               Zip Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [27]:
#now let us create a new dataframe to save the dataframe with index set. This is one kind of method. 
#The other method is discussed below using 'inplace' keyword.
df9= df8.set_index("ID")
df9

Address           City               Zip Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [28]:
df8.set_index("ID", inplace=True)
df8

Address           City               Zip Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [29]:
#In case, if we need to change the index, we can moidify as per the below code
df8.set_index("Address", inplace=True)
df8
#Please understand that the new index 'Address' is set. However, the old index with 'ID' is disappeared. 

City               Zip Country         Name  \
Address                                                                 
3666 21st St     San Francisco          CA 94114     USA      Madeira   
735 Dolores St   San Francisco          CA 94119     USA  Bready Shop   
332 Hill St      San Francisco  California 94114     USA  Super River   
3995 23rd St     San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St  San Francisco        California     USA      Sanchez   
551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

#### Index and Slicing

In [ ]:
#Now lets try to slice and index the dataframe.
#Please see that our dataframe has column label and index label.

<b>Pandas Indexing using [ ], .loc[], .iloc[ ], .ix[ ]</b>

There are a lot of ways to pull the elements, rows, and columns from a DataFrame. There are some indexing method in Pandas which help in getting an element from a DataFrame. These indexing methods appear very similar but behave very differently. Pandas support four types of Multi-axes indexing they are:


- Dataframe.[ ] ; This function also known as indexing operator
- Dataframe.loc[ ] : This function is used for labels.
- Dataframe.iloc[ ] : This function is used for positions or integer based
- Dataframe.ix[] : This function is used for both label and integer based

Collectively, they are called the <b>indexers</b>. These are by far the most common ways to index data. These are four function which help in getting the elements, rows, and columns from a DataFrame.

<b>Indexing a Dataframe using indexing operator [] :</b>

Indexing operator is used to refer to the square brackets following an object. The .loc and .iloc indexers also use the indexing operator to make selections. In this indexing operator to refer to df[].

In [31]:
#retrieving single column by indexing operator 
first_data = df8['City']
first_data

Address
3666 21st St       San Francisco
735 Dolores St     San Francisco
332 Hill St        San Francisco
3995 23rd St       San Francisco
1056 Sanchez St    San Francisco
551 Alvarado St    San Francisco
Name: City, dtype: object

In [36]:
# retrieving multiple columns by indexing operator 
first = df8[['City', 'Zip','Country']]
first

City               Zip Country
Address                                                 
3666 21st St     San Francisco          CA 94114     USA
735 Dolores St   San Francisco          CA 94119     USA
332 Hill St      San Francisco  California 94114     USA
3995 23rd St     San Francisco          CA 94114     USA
1056 Sanchez St  San Francisco        California     USA
551 Alvarado St  San Francisco          CA 94114     USA

<b>Indexing a DataFrame using .loc[ ] :</b>

This function selects data by the label of the rows and columns. The df.loc indexer selects data in a different way than just the indexing operator. It can select subsets of rows or columns. It can also simultaneously select subsets of rows and columns.

In [38]:
first = df8.loc["3666 21st St"] 
first

City         San Francisco
Zip               CA 94114
Country                USA
Name               Madeira
Employees                8
Name: 3666 21st St, dtype: object

In [39]:
second = df8.loc["735 Dolores St"]
second

City         San Francisco
Zip               CA 94119
Country                USA
Name           Bready Shop
Employees               15
Name: 735 Dolores St, dtype: object

In [41]:
#Selecting multiple rows
first = df8.loc[["3666 21st St", "735 Dolores St"]] 
first

City       Zip Country         Name  Employees
Address                                                                
3666 21st St    San Francisco  CA 94114     USA      Madeira          8
735 Dolores St  San Francisco  CA 94119     USA  Bready Shop         15

<b>Selecting all of the rows and some columns</b>

In order to select all of the rows and some columns, we use single colon [:] to select all of rows and list of some columns which we want to select like this:

In [43]:
first = df8.loc[:, ["City", "Zip", "Country"]] 
first

City               Zip Country
Address                                                 
3666 21st St     San Francisco          CA 94114     USA
735 Dolores St   San Francisco          CA 94119     USA
332 Hill St      San Francisco  California 94114     USA
3995 23rd St     San Francisco          CA 94114     USA
1056 Sanchez St  San Francisco        California     USA
551 Alvarado St  San Francisco          CA 94114     USA

<b>Indexing a DataFrame using .iloc[ ] :</b>

This function allows us to retrieve rows and columns by position. In order to do that, we’ll need to specify the positions of the rows that we want, and the positions of the columns that we want as well. The df.iloc indexer is very similar to df.loc but only uses integer locations to make its selections.

<b>Selecting a single row</b>

In [47]:
row2 = df8.iloc [[1]] 
row2

City       Zip Country         Name  Employees
Address                                                                
735 Dolores St  San Francisco  CA 94119     USA  Bready Shop         15

In [49]:
# retrieving multiple rows by iloc method  
row2 = df8.iloc [[1,2,3]] 
row2

City               Zip Country         Name  \
Address                                                                
735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St     San Francisco  California 94114     USA  Super River   
3995 23rd St    San Francisco          CA 94114     USA   Ben's Shop   

                Employees  
Address                    
735 Dolores St         15  
332 Hill St            25  
3995 23rd St           10

<b>Selecting two rows and two columns</b>

In order to select two rows and two columns, we create a list of 2 integer for rows and list of 2 integer for columns then pass to a .iloc[] function.

In [51]:
row2 = df8.iloc [[3, 4], [1, 2]] 
(row2) 

Zip Country
Address                            
3995 23rd St       CA 94114     USA
1056 Sanchez St  California     USA

In [53]:
# retrieving all rows and some columns by iloc method  
row2 = df8.iloc [:, [1, 2]] 
(row2) 

Zip Country
Address                                  
3666 21st St             CA 94114     USA
735 Dolores St           CA 94119     USA
332 Hill St      California 94114     USA
3995 23rd St             CA 94114     USA
1056 Sanchez St        California     USA
551 Alvarado St          CA 94114     USA

<b>Indexing a using Dataframe.ix[ ] :</b>

Early in the development of pandas, there existed another indexer, ix. This indexer was capable of selecting both by label and by integer location. While it was versatile, it caused lots of confusion because it’s not explicit. Sometimes integers can also be labels for rows or columns. Thus there were instances where it was ambiguous. Generally, ix is label based and acts just as the .loc indexer. However, .ix also supports integer type selections (as in .iloc) where passed an integer. This only works where the index of the DataFrame is not integer based .ix will accept any of the inputs of .loc and .iloc.
Note: The .ix indexer has been deprecated in recent versions of Pandas.

<b>Selecting a single row using .ix[] as .loc[]</b>

In [54]:
first = df8.ix["3666 21st St"]
first

C:\Users\Rajesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


City         San Francisco
Zip               CA 94114
Country                USA
Name               Madeira
Employees                8
Name: 3666 21st St, dtype: object

In order to select a single row, we can pass a single integer to .ix[] function. This function similar as a iloc[] function if we pass an integer in a .ix[] function.

In [55]:
first = df8.ix[1] 
first

C:\Users\Rajesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


City         San Francisco
Zip               CA 94119
Country                USA
Name           Bready Shop
Employees               15
Name: 735 Dolores St, dtype: object

#### Deleting Columns and rows

Python is a great language for doing data analysis, primarily because of the fantastic ecosystem of data-centric Python packages. Pandas is one of those packages and makes importing and analyzing data much easier.

Pandas provide data analysts a way to delete and filter data frame using .drop() method. Rows or columns can be removed using index label or column name using this method.

<b>Dropping Rows by index label</b>

In [58]:
df8

City               Zip Country         Name  \
Address                                                                 
3666 21st St     San Francisco          CA 94114     USA      Madeira   
735 Dolores St   San Francisco          CA 94119     USA  Bready Shop   
332 Hill St      San Francisco  California 94114     USA  Super River   
3995 23rd St     San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St  San Francisco        California     USA      Sanchez   
551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [61]:
df8.drop(["551 Alvarado St"]) 

City               Zip Country         Name  \
Address                                                                 
3666 21st St     San Francisco          CA 94114     USA      Madeira   
735 Dolores St   San Francisco          CA 94119     USA  Bready Shop   
332 Hill St      San Francisco  California 94114     USA  Super River   
3995 23rd St     San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St  San Francisco        California     USA      Sanchez   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12

<b>Dropping columns with column name</b>

In [63]:
df8.drop(["City"], axis = 1) 

Zip Country         Name  Employees
Address                                                          
3666 21st St             CA 94114     USA      Madeira          8
735 Dolores St           CA 94119     USA  Bready Shop         15
332 Hill St      California 94114     USA  Super River         25
3995 23rd St             CA 94114     USA   Ben's Shop         10
1056 Sanchez St        California     USA      Sanchez         12
551 Alvarado St          CA 94114     USA   Richvalley         20

As shown in the output images, the new output doesn’t have the passed columns. Those values were dropped since axis was set equal to 1 and the changes were not be made in the original data frame since inplace was not given True.


#### Updating  and Adding new Columns and Rows

In [65]:
df8['Continent']= df8.shape[0]*['North America']
df8

City               Zip Country         Name  \
Address                                                                 
3666 21st St     San Francisco          CA 94114     USA      Madeira   
735 Dolores St   San Francisco          CA 94119     USA  Bready Shop   
332 Hill St      San Francisco  California 94114     USA  Super River   
3995 23rd St     San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St  San Francisco        California     USA      Sanchez   
551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

                 Employees      Continent  
Address                                    
3666 21st St             8  North America  
735 Dolores St          15  North America  
332 Hill St             25  North America  
3995 23rd St            10  North America  
1056 Sanchez St         12  North America  
551 Alvarado St         20  North America

In [66]:
#Just tried to explain what is the df8.shape added above
df8.shape

(6, 6)

In [67]:
df8.shape[0]

6

In [68]:
df8.shape[0]*['North America']

['North America',
 'North America',
 'North America',
 'North America',
 'North America',
 'North America']

#### How to add a new row to a dataframe

In [70]:
#Adding Transpose to a dataframe
df8_t=df8.T
df8_t

Address     3666 21st St 735 Dolores St       332 Hill St   3995 23rd St  \
City       San Francisco  San Francisco     San Francisco  San Francisco   
Zip             CA 94114       CA 94119  California 94114       CA 94114   
Country              USA            USA               USA            USA   
Name             Madeira    Bready Shop       Super River     Ben's Shop   
Employees              8             15                25             10   
Continent  North America  North America     North America  North America   

Address   1056 Sanchez St 551 Alvarado St  
City        San Francisco   San Francisco  
Zip            California        CA 94114  
Country               USA             USA  
Name              Sanchez      Richvalley  
Employees              12              20  
Continent   North America   North America

In [71]:
df8_t['My Address']=['My City',10,'My Country','My shop', 7,'North America']
df8_t

Address     3666 21st St 735 Dolores St       332 Hill St   3995 23rd St  \
City       San Francisco  San Francisco     San Francisco  San Francisco   
Zip             CA 94114       CA 94119  California 94114       CA 94114   
Country              USA            USA               USA            USA   
Name             Madeira    Bready Shop       Super River     Ben's Shop   
Employees              8             15                25             10   
Continent  North America  North America     North America  North America   

Address   1056 Sanchez St 551 Alvarado St     My Address  
City        San Francisco   San Francisco        My City  
Zip            California        CA 94114             10  
Country               USA             USA     My Country  
Name              Sanchez      Richvalley        My shop  
Employees              12              20              7  
Continent   North America   North America  North America

In [72]:
df8_t.T #(Adding a transpose once again to bring back the dataframe to its original shape. This is one of the easiest method to add a new row to DF)

City               Zip     Country         Name  \
Address                                                                     
3666 21st St     San Francisco          CA 94114         USA      Madeira   
735 Dolores St   San Francisco          CA 94119         USA  Bready Shop   
332 Hill St      San Francisco  California 94114         USA  Super River   
3995 23rd St     San Francisco          CA 94114         USA   Ben's Shop   
1056 Sanchez St  San Francisco        California         USA      Sanchez   
551 Alvarado St  San Francisco          CA 94114         USA   Richvalley   
My Address             My City                10  My Country      My shop   

                Employees      Continent  
Address                                   
3666 21st St            8  North America  
735 Dolores St         15  North America  
332 Hill St            25  North America  
3995 23rd St           10  North America  
1056 Sanchez St        12  North America  
551 Alvarado St        20  North America  
My Address              7  North America

## NUMPY ILLUSTRATIONS (Numerical Python)

In [100]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [39]:
import numpy as np
n= np.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [26]:
type(n)   #---> This is a one dimensional array

numpy.ndarray

In [27]:
#Now let us create a two dimensional array
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [28]:
#Now let us create a three dimensional array
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#### Numpy is a general requirement for many other libraries.

In [3]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


Installing OpenCV

Let us install OpenCV (Computer Vision) to convert the images to Numpy arrays

In [29]:
import cv2
img=cv2.imread("smallgray.png",0)
print(img)
#--->Here 0 represents that the image is read in grayscale 
# and incase if we pass 1, then it is BGR (Blue green and Red)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [30]:
img1=cv2.imread("smallgray.png",1)
print(img1)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [31]:
import os
os.getcwd()

'C:\\Users\\Rajesh\\Downloads'

In [32]:
#To Copy the image to a location
cv2.imwrite("new_image.png",img)

True

In [33]:
#Indexing and sliching the array
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [37]:
#Lets extract [198,125] and [125,134] from the 2nd and 3rd line
img[1:,0:2]

array([[198, 125],
       [209, 134]], dtype=uint8)

In [38]:
#Lets now try to extract the number 97 from row 3 and column 4 
img[2,3]

97

In [40]:
#Stacking Numpy arrays
#HSTACK -HORIZONTAL STACK

ims=np.hstack((img,img))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [52]:
#VSTACK -VERTICAL STACK
ims1=np.vstack((img,img))
ims1
#Please remember that if we try to concatenate the array of diff dimensions, then the error will appear

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [53]:
#Splitting Numpy arrays
#HSPLI- Horizontal Split
lst=np.hsplit(ims1,5)
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [54]:
#VSPLIT-Vertical Split
lst=np.vsplit(ims1,3)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

## Let's create a small project using Numpy, Pandas and Computer Vision to implement the above learnings. Please find my github repositories to know more...

## Thank You!